#!/bin/bash

# Function to enable DNS changer
function start_dns_changer {
    source /usr/share/kali-whoami/assets/sources/config

    if [[ "$ip_changer_status" == "Disable" ]]; then
        # Backup and configure nameservers
        if [[ "$dns_changer_status" == "Disable" ]]; then
            cat /etc/resolv.conf > "$BACKUPDIR/resolv.conf.bak"
            cat > "/etc/resolv.conf" <<EOF
# generated by whoami
nameserver 84.200.69.80
nameserver 84.200.70.40
nameserver 91.239.100.100
nameserver 89.233.43.71
nameserver 208.67.222.222
nameserver 208.67.220.220
EOF
            sed -i 's/dns_changer_status="Disable"/dns_changer_status="Enable"/g' "$SRCDIR/sources/config"
            echo "[INFO] DNS changer successfully enabled"
        else
            echo "[WARN] DNS changer is already running"
        fi
    else
        echo "[WARN] The DNS changer is not available. (IP changer enabled)"
    fi
}

# Function to disable DNS changer
function stop_dns_changer {
    source /usr/share/kali-whoami/assets/sources/config
    cat "$BACKUPDIR/resolv.conf.bak" > /etc/resolv.conf && rm -f "$BACKUPDIR/resolv.conf.bak"
    sed -i 's/dns_changer_status="Enable"/dns_changer_status="Disable"/g' "$SRCDIR/sources/config"
    echo "[INFO] DNS changer successfully disabled"
}

# Main script logic
case "$1" in
    "start")
        start_dns_changer
        ;;
    "stop")
        stop_dns_changer
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac